# Generated by Django 6.0.5 on 2026-05-07 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_telp', models.CharField(blank=True, max_length=15, null=True)),
                ('level', models.CharField(choices=[('kader', 'Kader'), ('bidan', 'Bidan'), ('admin', 'Admin')], max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petugas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petugas',
                'verbose_name_plural': 'Petugas',
                'db_table': 'petugas',
                'ordering': ['nama'],
            },
        ),
    ]
