# Generated by Django 6.0.5 on 2026-05-07 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posyandu', '0002_alter_penugasanpetugas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petugas',
            name='posyandu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kader', to='posyandu.posyandu'),
        ),
    ]
