# Generated by Django 6.0.5 on 2026-05-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_petugas_posyandu'),
        ('posyandu', '0002_alter_penugasanpetugas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petugas',
            options={'ordering': ['nama']},
        ),
        migrations.AlterField(
            model_name='petugas',
            name='posyandu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petugas', to='posyandu.posyandu'),
        ),
    ]
