# Generated by Django 6.0.5 on 2026-05-07 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('peserta', '0001_initial'),
        ('posyandu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PemeriksaanBalita',
            fields=[
                ('id_periksa', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_pemeriksaan', models.DateTimeField(default=django.utils.timezone.now)),
                ('usia_bulan', models.IntegerField(blank=True, null=True)),
                ('berat_badan', models.FloatField(blank=True, null=True)),
                ('tinggi_badan', models.FloatField(blank=True, null=True)),
                ('lila_balita', models.FloatField(blank=True, null=True)),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('hsl_prediksi', models.CharField(blank=True, max_length=30, null=True)),
                ('probabilitas', models.FloatField(default=0)),
                ('status_kesehatan', models.CharField(max_length=255)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posyandu.jadwalkegiatan')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peserta.peserta')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.petugas')),
            ],
            options={
                'verbose_name': 'Pemeriksaan Balita',
                'verbose_name_plural': 'Pemeriksaan Balita',
                'db_table': 'pemeriksaan_balita',
                'ordering': ['-tgl_pemeriksaan'],
            },
        ),
        migrations.CreateModel(
            name='Imunisasi',
            fields=[
                ('id_imunisasi', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_vaksin', models.CharField(choices=[('HB-0', 'HB-0'), ('BCG', 'BCG'), ('Polio 1', 'Polio 1'), ('Polio 2', 'Polio 2'), ('Polio 3', 'Polio 3'), ('Polio 4', 'Polio 4'), ('DPT-HB-Hib 1', 'DPT-HB-Hib 1'), ('DPT-HB-Hib 2', 'DPT-HB-Hib 2'), ('DPT-HB-Hib 3', 'DPT-HB-Hib 3'), ('Campak/MR', 'Campak/MR'), ('PCV', 'PCV'), ('IPV', 'IPV')], max_length=50)),
                ('dosis', models.CharField(choices=[('1', 'Dosis 1'), ('2', 'Dosis 2'), ('3', 'Dosis 3'), ('4', 'Dosis 4'), ('Booster', 'Booster')], default='1', max_length=20)),
                ('usia_saat_vaksin', models.IntegerField(help_text='Usia balita dalam bulan')),
                ('tgl_pemberian', models.DateField(default=django.utils.timezone.now)),
                ('lokasi', models.CharField(blank=True, max_length=100, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posyandu.jadwalkegiatan')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peserta.peserta')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Imunisasi',
                'verbose_name_plural': 'Data Imunisasi Balita',
                'db_table': 'imunisasi',
                'unique_together': {('peserta', 'jadwal', 'jenis_vaksin')},
            },
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id_kehadiran', models.AutoField(primary_key=True, serialize=False)),
                ('status_kehadiran', models.CharField(choices=[('hadir', 'Hadir'), ('tidak', 'Tidak Hadir'), ('izin', 'Izin')], default='tidak', max_length=20)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posyandu.jadwalkegiatan')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peserta.peserta')),
            ],
            options={
                'db_table': 'kehadiran',
                'ordering': ['jadwal'],
                'unique_together': {('peserta', 'jadwal')},
            },
        ),
    ]
