# Generated by Django 6.0.5 on 2026-05-09 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_petugas_options_alter_petugas_posyandu'),
        ('pemeriksaan', '0001_initial'),
        ('peserta', '0002_remove_peserta_usia'),
        ('posyandu', '0003_alter_jadwalkegiatan_jns_kegiatan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemeriksaanbalita',
            name='status_kesehatan',
        ),
        migrations.AddField(
            model_name='pemeriksaanbalita',
            name='akurasi_model',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemeriksaanbalita',
            name='lingkar_kepala',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pemeriksaanbalita',
            name='status_gizi',
            field=models.CharField(choices=[('normal', 'Normal'), ('stunting', 'Stunting'), ('gizi_kurang', 'Gizi Kurang'), ('gizi_buruk', 'Gizi Buruk')], default='normal', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='pemeriksaanbalita',
            name='versi_model',
            field=models.CharField(default='RF_v1', max_length=20),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imunisasi', to='posyandu.jadwalkegiatan'),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='peserta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imunisasi', to='peserta.peserta'),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imunisasi', to='accounts.petugas'),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kehadiran', to='posyandu.jadwalkegiatan'),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='peserta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kehadiran', to='peserta.peserta'),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='berat_badan',
            field=models.FloatField(blank=True, help_text='Kg', null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemeriksaan_balita', to='posyandu.jadwalkegiatan'),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='lila_balita',
            field=models.FloatField(blank=True, help_text='Lingkar Lengan Atas', null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='peserta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemeriksaan_balita', to='peserta.peserta'),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemeriksaan_balita', to='accounts.petugas'),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='probabilitas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='tinggi_badan',
            field=models.FloatField(blank=True, help_text='Cm', null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='usia_bulan',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='PemeriksaanBumil',
            fields=[
                ('id_periksa', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_pemeriksaan', models.DateTimeField(default=django.utils.timezone.now)),
                ('usia_kehamilan', models.IntegerField(help_text='Usia kehamilan dalam minggu')),
                ('berat_badan', models.FloatField(blank=True, help_text='Kg', null=True)),
                ('tinggi_badan', models.FloatField(blank=True, help_text='Cm', null=True)),
                ('lila_bumil', models.FloatField(help_text='Lingkar Lengan Atas')),
                ('tekanan_darah', models.CharField(help_text='Contoh: 120/80', max_length=20)),
                ('tinggi_fundus', models.FloatField(blank=True, help_text='Cm', null=True)),
                ('denyut_jantung_janin', models.IntegerField(blank=True, help_text='DJJ', null=True)),
                ('hemoglobin', models.FloatField(blank=True, help_text='Hb', null=True)),
                ('status_kehamilan', models.CharField(choices=[('normal', 'Normal'), ('resiko', 'Resiko Tinggi'), ('anemia', 'Anemia'), ('kek', 'KEK')], default='normal', max_length=30)),
                ('keluhan', models.TextField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('perlu_rujukan', models.BooleanField(default=False)),
                ('tujuan_rujukan', models.CharField(blank=True, max_length=255, null=True)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posyandu.jadwalkegiatan')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemeriksaan_bumil', to='peserta.peserta')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.petugas')),
            ],
            options={
                'db_table': 'pemeriksaan_bumil',
                'ordering': ['-tgl_pemeriksaan'],
            },
        ),
    ]
