# Generated by Django 6.0.5 on 2026-05-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemeriksaan', '0002_remove_pemeriksaanbalita_status_kesehatan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemeriksaanbalita',
            name='akurasi_model',
        ),
        migrations.RemoveField(
            model_name='pemeriksaanbalita',
            name='versi_model',
        ),
    ]
