# Generated by Django 6.0.5 on 2026-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemeriksaan', '0003_remove_pemeriksaanbalita_akurasi_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imunisasi',
            options={'verbose_name': 'Data Imunisasi', 'verbose_name_plural': 'Data Imunisasi'},
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='dosis',
            field=models.CharField(blank=True, choices=[('1', 'Dosis 1'), ('2', 'Dosis 2'), ('3', 'Dosis 3'), ('4', 'Dosis 4'), ('Booster', 'Booster')], default='1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='jenis_vaksin',
            field=models.CharField(choices=[('HB-0', 'HB-0'), ('BCG', 'BCG'), ('Polio 1', 'Polio 1'), ('Polio 2', 'Polio 2'), ('Polio 3', 'Polio 3'), ('Polio 4', 'Polio 4'), ('DPT-HB-Hib 1', 'DPT-HB-Hib 1'), ('DPT-HB-Hib 2', 'DPT-HB-Hib 2'), ('DPT-HB-Hib 3', 'DPT-HB-Hib 3'), ('Campak/MR', 'Campak/MR'), ('PCV', 'PCV'), ('IPV', 'IPV'), ('TT-1', 'TT-1 (Tetanus Toksoid)'), ('TT-2', 'TT-2 (Tetanus Toksoid)'), ('TT-3', 'TT-3 (Tetanus Toksoid)'), ('TT-4', 'TT-4 (Tetanus Toksoid)'), ('TT-5', 'TT-5 (Tetanus Toksoid)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='usia_saat_vaksin',
            field=models.IntegerField(blank=True, help_text='Usia dalam bulan (balita) atau minggu kehamilan (bumil)', null=True),
        ),
    ]
