# Generated by Django 6.0.5 on 2026-06-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemeriksaan', '0004_alter_imunisasi_options_alter_imunisasi_dosis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pemeriksaanbalita',
            options={'ordering': ['-tgl_pemeriksaan']},
        ),
        migrations.RemoveField(
            model_name='pemeriksaanbalita',
            name='probabilitas',
        ),
        migrations.AddField(
            model_name='pemeriksaanbalita',
            name='prob_ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='berat_badan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='lila_balita',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='status_gizi',
            field=models.CharField(choices=[('normal', 'Normal'), ('risiko', 'Risiko Stunting'), ('stunting', 'Stunting'), ('stunting_berat', 'Stunting Berat')], default='normal', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='tinggi_badan',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
