# Generated by Django 6.0.5 on 2026-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemeriksaan', '0005_alter_pemeriksaanbalita_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imunisasi',
            name='usia_kehamilan',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Usia kehamilan dalam minggu', null=True),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='dosis',
            field=models.CharField(blank=True, choices=[('1', 'Dosis 1'), ('2', 'Dosis 2'), ('3', 'Dosis 3'), ('4', 'Dosis 4'), ('5', 'Dosis 5'), ('Booster', 'Booster')], default='1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imunisasi',
            name='usia_saat_vaksin',
            field=models.IntegerField(blank=True, help_text='Usia dalam bulan (balita)', null=True),
        ),
    ]
