# Generated by Django 6.0.5 on 2026-08-06 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemeriksaan', '0006_imunisasi_usia_kehamilan_alter_imunisasi_dosis_and_more'),
        ('posyandu', '0004_posyandu_desa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imunisasi',
            name='jenis_vaksin',
            field=models.CharField(choices=[('HB-0', 'HB-0'), ('BCG', 'BCG'), ('Polio 1', 'Polio 1'), ('Polio 2', 'Polio 2'), ('Polio 3', 'Polio 3'), ('Polio 4', 'Polio 4'), ('DPT-HB-Hib 1', 'DPT-HB-Hib 1'), ('DPT-HB-Hib 2', 'DPT-HB-Hib 2'), ('DPT-HB-Hib 3', 'DPT-HB-Hib 3'), ('Campak/MR', 'Campak/MR'), ('PCV 1', 'PCV 1'), ('PCV 2', 'PCV 2'), ('PCV Booster', 'PCV Booster'), ('IPV', 'IPV'), ('TT-1', 'TT-1 (Tetanus Toksoid)'), ('TT-2', 'TT-2 (Tetanus Toksoid)'), ('TT-3', 'TT-3 (Tetanus Toksoid)'), ('TT-4', 'TT-4 (Tetanus Toksoid)'), ('TT-5', 'TT-5 (Tetanus Toksoid)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbumil',
            name='jadwal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemeriksaan_bumil', to='posyandu.jadwalkegiatan'),
        ),
    ]
