# Generated by Django 6.0.5 on 2026-08-28 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_petugas_options_alter_petugas_posyandu'),
        ('pemeriksaan', '0007_alter_imunisasi_jenis_vaksin_and_more'),
        ('peserta', '0007_peserta_lila_lahir_alter_peserta_nik_ibu_and_more'),
        ('posyandu', '0004_posyandu_desa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelayananBalita',
            fields=[
                ('id_pelayanan', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_layanan', models.CharField(choices=[('vitamin_a', 'Vitamin A'), ('obat_cacing', 'Obat Cacing')], max_length=30)),
                ('tanggal_pemberian', models.DateField(default=django.utils.timezone.now)),
                ('jenis_vitamin_a', models.CharField(blank=True, choices=[('biru', 'Vitamin A Biru'), ('merah', 'Vitamin A Merah')], max_length=20, null=True)),
                ('nama_obat', models.CharField(blank=True, max_length=100, null=True)),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pelayanan Balita',
                'verbose_name_plural': 'Pelayanan Balita',
                'db_table': 'pelayanan_balita',
                'ordering': ['-tanggal_pemberian'],
            },
        ),
        migrations.AlterModelOptions(
            name='pemeriksaanbalita',
            options={'ordering': ['-tgl_pemeriksaan'], 'verbose_name': 'Pemeriksaan Balita', 'verbose_name_plural': 'Pemeriksaan Balita'},
        ),
        migrations.AlterModelOptions(
            name='pemeriksaanbumil',
            options={'ordering': ['-tgl_pemeriksaan'], 'verbose_name': 'Pemeriksaan Ibu Hamil', 'verbose_name_plural': 'Pemeriksaan Ibu Hamil'},
        ),
        migrations.AlterUniqueTogether(
            name='imunisasi',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='kehadiran',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='berat_badan',
            field=models.FloatField(blank=True, help_text='Berat badan dalam kilogram', null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='lila_balita',
            field=models.FloatField(blank=True, help_text='Lingkar lengan atas balita dalam sentimeter', null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='lingkar_kepala',
            field=models.FloatField(blank=True, help_text='Lingkar kepala balita dalam sentimeter', null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbalita',
            name='tinggi_badan',
            field=models.FloatField(blank=True, help_text='Panjang/Tinggi badan dalam sentimeter', null=True),
        ),
        migrations.AlterField(
            model_name='pemeriksaanbumil',
            name='petugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemeriksaan_bumil', to='accounts.petugas'),
        ),
        migrations.AddConstraint(
            model_name='imunisasi',
            constraint=models.UniqueConstraint(fields=('peserta', 'jadwal', 'jenis_vaksin'), name='unique_imunisasi_peserta_jadwal_vaksin'),
        ),
        migrations.AddConstraint(
            model_name='kehadiran',
            constraint=models.UniqueConstraint(fields=('peserta', 'jadwal'), name='unique_kehadiran_peserta_jadwal'),
        ),
        migrations.AddField(
            model_name='pelayananbalita',
            name='pemeriksaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelayanan_balita', to='pemeriksaan.pemeriksaanbalita'),
        ),
        migrations.AddConstraint(
            model_name='pelayananbalita',
            constraint=models.UniqueConstraint(fields=('pemeriksaan', 'jenis_layanan'), name='unique_pelayanan_per_pemeriksaan'),
        ),
    ]
