# Generated by Django 5.2.17 on 2026-10-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pemeriksaan", "0011_usia_hari_dan_rekalkulasi_who"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pemeriksaanbalita",
            name="usia_bulan",
            field=models.IntegerField(
                blank=True,
                editable=False,
                help_text="Usia bulan penuh untuk fitur Random Forest dan laporan",
                null=True,
            ),
        ),
    ]
