# Generated by Django 6.0.5 on 2026-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WHOStandardPBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('month', models.PositiveIntegerField(help_text='Umur dalam bulan (0-60)')),
                ('l_value', models.FloatField()),
                ('m_value', models.FloatField()),
                ('s_value', models.FloatField()),
                ('sd3neg', models.FloatField()),
                ('sd2neg', models.FloatField()),
                ('sd1neg', models.FloatField()),
                ('sd0', models.FloatField()),
                ('sd1', models.FloatField()),
                ('sd2', models.FloatField()),
                ('sd3', models.FloatField()),
            ],
            options={
                'db_table': 'who_standard_pbu',
                'ordering': ['gender', 'month'],
                'constraints': [models.UniqueConstraint(fields=('gender', 'month'), name='unique_pbu_gender_month')],
            },
        ),
    ]
