# Generated by Django 6.0.5 on 2026-06-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whostandardpbu',
            name='sd',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
