# Generated by Django 6.0.5 on 2026-05-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posyandu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Posyandu',
                'verbose_name_plural': 'Posyandu',
                'db_table': 'posyandu',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='PenugasanPetugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.petugas')),
                ('posyandu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posyandu.posyandu')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalKegiatan',
            fields=[
                ('id_jadwal', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_kegiatan', models.DateField(verbose_name='Tanggal Kegiatan')),
                ('jam_mulai', models.TimeField(verbose_name='Jam Mulai')),
                ('jam_selesai', models.TimeField(verbose_name='Jam Selesai')),
                ('jns_kegiatan', models.CharField(choices=[('Pemeriksaan Rutin', 'Pemeriksaan Rutin'), ('Imunisasi', 'Imunisasi')], max_length=50, verbose_name='Jenis Kegiatan')),
                ('posyandu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posyandu.posyandu')),
            ],
            options={
                'verbose_name': 'Jadwal Kegiatan',
                'verbose_name_plural': 'Jadwal Kegiatan',
                'db_table': 'jadwal_kegiatan',
                'ordering': ['-tgl_kegiatan'],
            },
        ),
    ]
