# Generated by Django 6.0.5 on 2026-05-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posyandu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penugasanpetugas',
            options={'verbose_name': 'Penugasan Petugas', 'verbose_name_plural': 'Penugasan Petugas'},
        ),
        migrations.AlterModelTable(
            name='penugasanpetugas',
            table='penugasan_Petugas',
        ),
    ]
