# Generated by Django 6.0.5 on 2026-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posyandu', '0002_alter_penugasanpetugas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalkegiatan',
            name='jns_kegiatan',
            field=models.CharField(choices=[('Pemeriksaan Rutin', 'Pemeriksaan Rutin'), ('Imunisasi', 'Imunisasi'), ('Penimbangan', 'Penimbangan'), ('Vitamin', 'Vitamin'), ('Kelas Ibu Hamil', 'Kelas Ibu Hamil')], max_length=50, verbose_name='Jenis Kegiatan'),
        ),
    ]
