# Generated by Django 6.0.5 on 2026-06-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posyandu', '0003_alter_jadwalkegiatan_jns_kegiatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='posyandu',
            name='desa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
