# Generated by Django 6.0.5 on 2026-05-07 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posyandu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peserta', models.CharField(max_length=50)),
                ('tgl_lahir', models.DateField()),
                ('usia', models.CharField(blank=True, max_length=3, null=True)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('status_peserta', models.CharField(choices=[('ibu hamil', 'Ibu Hamil'), ('balita', 'Balita')], max_length=10)),
                ('nama_ibu', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=20, null=True)),
                ('is_tamu', models.BooleanField(default=False)),
                ('asal_posyandu', models.CharField(blank=True, max_length=100, null=True)),
                ('posko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posyandu.posyandu')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'peserta',
                'ordering': ['-nama_peserta'],
            },
        ),
    ]
