# Generated by Django 6.0.5 on 2026-05-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peserta',
            name='usia',
        ),
    ]
