# Generated by Django 6.0.5 on 2026-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0002_remove_peserta_usia'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='anak_ke',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='nama_ayah',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Ayah'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nama_ibu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Ibu'),
        ),
    ]
