# Generated by Django 6.0.5 on 2026-06-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0003_peserta_anak_ke_peserta_nama_ayah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='no_nik',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
