# Generated by Django 6.0.5 on 2026-06-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0004_peserta_no_nik'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='bb_lahir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Berat Badan Lahir (Kg)'),
        ),
        migrations.AddField(
            model_name='peserta',
            name='tb_lahir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Panjang Badan Lahir (Cm)'),
        ),
    ]
