# Generated by Django 6.0.5 on 2026-06-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0005_peserta_bb_lahir_peserta_tb_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='nik_ibu',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
