# Generated by Django 6.0.5 on 2026-06-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peserta', '0006_peserta_nik_ibu'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='lila_lahir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lingkar Lengan Lahir (Cm)'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nik_ibu',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='no_nik',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
